### ISSUE TITLE
Best way to have an install / update rolling job for specific set of tools?

### ISSUE THREAD

**Issue by pcm32** [galaxyproject/galaxy-helm#115]
At this point we have deployments on multiple setups, including none cloud ones. So we keep all the tools that we want to have installed in our instances on a yaml file on a git repo from where ephemeris can install from a toolshed. We have some centralised CI that updates tools on each instance whenever there are changes in the git repo with the yaml files, for our non-cloud deployents.

On spin of a new instance with the helm chart, I would like to have a k8s job that runs once Galaxy is operational, possibly using a master API key, to run ephemeris using a desired git repo and install those tools. Then I would like to have that running with some periodicity, I guess through a cronjob, to have tools updated as new revisions come.

As such, I see this as a Job (for the first run) and a Cron Job (for subsequent runs), but of course I don't like the duplication arising there.

When running with multiple web processes, I have noticed that after you have installed a number of tools not all web processes see all tools, and restarting them fixes this. This would require I guess the newly implemented rollout restarts for deployments, which would need to be triggered via the service account I presume once the jobs succesfully installs/updates tools.

How would you do this? Would you use Jobs and Cron Jobs or a different strategy?

Thanks!

**Comment by almahmoud** [comment]
Jobs sound like a good fit in theory, and I believe cron jobs are the only way to do it for the periodic updates. If you’re doing this manually (w/ kubectl or through dashboard), jobs are probably your best bet.
If you are doing it through helm though, you might be able to “abuse” init containers for this and therefore not require any chart changes. It’s definitely not what they are meant for by design, but since helm upgrade will bring up the new pods without destroying the old ones, you can just run the ephemeris process in an init container in the new pod, which will communicate with the old web handlers that are still running, after which new web handlers will spin up for each of the old ones, destroying the old ones after it’s replacement is up and running. This would mean you don’t need to give the container any type of special access to manage cluster resources for it to trigger a restart, it will just happen due to the upgrade, and you get no downtime upgrading which might not be true if you trigger the handlers to restart manually, depending on how that is triggered. The only bad thing I can think of using this is that the command to run ephemeris should also make sure only one of them runs (since the init container is going to be attached to multiple pods if the handler is scaled up), while the others just wait. This can be done fairly easily, but might make it not worth the hassle of using init containers for this.

The ideal way to do this though (although there is no implementation for it as of now) is likely helm “pre-upgrade hooks” which would be a job that is run before the upgrade, so similarly communicate with the old web handlers, and also get the free restart triggered by the upgrade, hence no need for any restart mechanism. I’d say this should be fairly easy to implement, and if you can just design what you’d like to pass to the values section for ephemeris, I can potentially implement the pre-upgrade hook job to use those values.
