### ISSUE TITLE
Adding custom tools

### ISSUE THREAD

**Issue by nathanweeks** [galaxyproject/galaxy-helm#129]
Is there an elegant way to add custom tools in a (somewhat-)declarative way? I naively attempted to define a simple custom tool in the extraFileMappings resource:

```
# overrides.yaml
configs:
  tool_conf.xml: |
    ... copy/paste from galaxy-helm/galaxy/values.yaml ...
    <section id="mytool" name="My Tool">
      <tool file="mytool/mytool.xml" />
    </section>

extraFileMappings:
  /galaxy/server/tools/mytool/mytool.xml:
    useSecret: false
    applyToJob: true
    applyToWeb: true
    content:

  /galaxy/server/tools/mytool/mytool.py:
    useSecret: false
    applyToJob: true
    applyToWeb: true
    content:

```

And then set their "content" values from the corresponding files (using Helm 3.1.x):

```
helm upgrade galaxy ./galaxy-helm/galaxy --values overrides.yaml \
  --set-file 'extraFileMappings./galaxy/server/tools/mytool/mytool\.xml.content=relative/path/to/mytool\.xml' \
  --set-file 'extraFileMappings./galaxy/server/tools/mytool/mytool\.py.content=relative/path/to/mytool\.py'
```

However, configMaps created from extraFileMappings to not appear to be mounted in the k8s Job resource that's created to run the tool.

**Comment by pcm32** [comment]
Currently what I'm doing to install tools is to direct an ephemeris install tools process to the instance lifted inside the k8s cluster. This suits me because we have other running instances not on k8s and we want to have all our instances with the same tools. However, this is slow, so I want to migrate to a process where I add all installed tools and the sqlite db for tools to a container and then use it as an init container, from where I would copy these to the deployment.

**Comment by nuwang** [comment]
@nathanweeks I think you could map the tool xml and tool_conf.xml as shown in your example, but the tool code will need to be built as a container. I'd suggest building a new container with your py file, pushing it to docker hub, and adding a mapping in `container_mapper_rules.yml` to map your tool_id to the container.
