### ISSUE TITLE
Move requirements.yaml into the Chart dependencies

### ISSUE THREAD

**Issue by cyrilcros** [galaxyproject/galaxy-helm#155]
Please see this: https://helm.sh/docs/faq/#consolidation-of-requirements-yaml-into-chart-yaml
I am using ArgoCD and getting “requirements.lock is out of sync” errors when I try to install the Chart. For Helm v3 charts dependencies would be listed in the Chart.yaml.
Thanks!
EDIT: as an alternative either remove the requirements.lock file or keep it in sync after each commit...

**Comment by almahmoud** [comment]
I believe we're leaving them separately in order to remain Helm2 compatible. Is the out-of-sync error when git cloning or using the packaged charts?
@afgane @nuwang any thoughts on this? I would personally not mind removing the `.lock` file if we keep the versions specified, alternatively could have the CI update dependencies on every merge if that's desirable?

**Comment by nuwang** [comment]
I think it would make sense to drop Helm 2 support for future releases. It's been a while and Helm 2 is not all that secure by default, and we can just tag this existing branch in case there's anyone still using this on Helm 2. I'd propose a major new release of the chart with Helm 2 support dropped.

**Comment by cyrilcros** [comment]
@almahmoud I was only using the git cloning version, I use [Argocd](https://github.com/argoproj/argo-cd) to point to the galaxy folder of your repo and install your chart with customized values. That has been working well for me.
Thanks!

**Comment by almahmoud** [comment]
This is now done as of https://github.com/galaxyproject/galaxy-helm/commit/1aff5f6cd0f2cf6b5d9075111c38ed33f1102b7b#diff-334ae070c8649f3b020807c49db1049009f6001d9d34cf97c8fd90e6269ae21e
