### ISSUE TITLE
Sudden DB version issues

### ISSUE THREAD

**Issue by viktoriaas** [galaxyproject/galaxy-helm#296]
Hi, 
today I wanted to upgrade my galaxy helm chart. I only changed 2 options in `values.yaml` (added admin to galaxy config and removed conda) and the upgrade totally failed. Since then, I am unable to run helm-galaxy, I have installed and uninstalled it multiple times and I always get:

```Exception: Your database has version '176' but this code expects version '174'. To downgrade the database schema you have to checkout the Galaxy version that you were running previously. Please backup your database and then migrate the database schema by running 'sh manage_db.sh downgrade 174'.```

Do you please know how it could be fixed?

**Comment by almahmoud** [comment]
This is due to the migrations script not running. Depending on which version you're upgrading from, it's most likely because of the change from using an init container in the job handler to a kubernetes batch job for the migrations (to make handlers independently scalable and not tie migrations to a specific handler). This was one of the reasons for the major version bump (from v3 to v4).

One thing you might be able to try is running with `--set initJob.createDatabase=false` to expect the database to exist (we also started using `create_db.sh` with v4). This should hopefully make it work if you're upgrading a running instance from one of the latest v3 versions. If that doesn't help, it would most likely require an interactive debugging session to figure out what is wrong. I would be more than happy to schedule a zoom call and help you figure it out sometime this week.

**Comment by viktoriaas** [comment]
Hi, 
the matter is resolved, it was most likely caused by following action:
- the Kubernetes cluster administrator installed galaxy helm chart **v4** into the cluster and instructed the galaxy administrator just to perform `helm upgrade galaxy -f values.yaml` in case he wants to change something
- however, the galaxy administrator had the whole galaxy repository cloned locally but probably older version (possibly v3) and he performed an upgrade from the repository which broke the dependencies

I resolved this by uninstalling galaxy, uninstalling postgres (deployment, PVC, secrets, services) and removing everything connected to galaxy. Then everything started up. 

Thanks for the help, I'm closing now
